# Generated by Django 4.2.5 on 2023-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_fanpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpage",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="fanpage_avatars/"
            ),
        ),
    ]
