# Generated by Django 4.2.5 on 2023-11-30 07:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_fanpage", "0002_fanpage_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpage",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="default-slug",
                editable=False,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
