# Generated by Django 4.2.5 on 2023-11-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_fanpage", "0003_fanpage_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumFanpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Fanpage Album", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="albums_fanpage",
                        to="social_fanpage.postimagefanpage",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_fanpage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
