# Generated by Django 4.2.5 on 2023-11-30 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_fanpage", "0004_albumfanpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpagelike",
            name="comments_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fanpagelike",
            name="hidden_for_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="hidden_posts_fanpage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
