# Generated by Django 4.2.5 on 2023-11-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_fanpage", "0005_fanpagelike_comments_closed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fanpagelike",
            name="comments_closed",
        ),
        migrations.RemoveField(
            model_name="fanpagelike",
            name="hidden_for_users",
        ),
    ]
