# Generated by Django 4.2.5 on 2023-11-30 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_fanpage", "0007_fanpagepost_comments_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpage",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_of_pages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
