# Generated by Django 4.2.5 on 2023-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_fanpage", "0008_fanpage_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpage",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
