# Generated by Django 4.2.5 on 2023-11-30 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_fanpage", "0009_fanpage_is_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLikeFanpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fanpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_fanpage.fanpage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_fanpages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
