# Generated by Django 4.2.6 on 2023-10-30 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
