# Generated by Django 4.2.7 on 2023-11-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_group_access_group_admins_group_requires_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_backgrounds/'),
        ),
    ]
