# Generated by Django 4.2.5 on 2023-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0008_membership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="access",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="Public",
                max_length=10,
            ),
        ),
    ]
