# Generated by Django 4.2.5 on 2023-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0009_alter_group_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.FileField(upload_to="post_images/"),
        ),
    ]
