# Generated by Django 4.2.5 on 2023-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0010_alter_postimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(upload_to="post_images/"),
        ),
    ]
