# Generated by Django 4.2.5 on 2023-11-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0012_postvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvideo",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="social_network.post",
            ),
        ),
    ]
