# Generated by Django 4.2.5 on 2023-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0013_alter_postvideo_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_video",
            field=models.FileField(blank=True, null=True, upload_to="comment_videos/"),
        ),
    ]
