# Generated by Django 4.2.5 on 2023-11-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0014_comment_comment_image_comment_comment_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_image",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment_video",
        ),
        migrations.CreateModel(
            name="CommentVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="comment_videos/"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="social_network.comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment_images/"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="social_network.comment",
                    ),
                ),
            ],
        ),
    ]
