# Generated by Django 4.2.5 on 2023-11-18 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_network", "0015_remove_comment_comment_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hidden_for_users",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
