# Generated by Django 4.2.5 on 2023-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0016_post_hidden_for_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comments_closed",
            field=models.BooleanField(default=False),
        ),
    ]
