# Generated by Django 4.2.5 on 2023-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0017_comment_comments_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comments_closed",
        ),
        migrations.AddField(
            model_name="post",
            name="comments_closed",
            field=models.BooleanField(default=False),
        ),
    ]
