# Generated by Django 4.2.5 on 2023-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0019_alter_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_posts",
            field=models.ManyToManyField(
                related_name="saved_by_profiles", to="social_network.post"
            ),
        ),
    ]
