# Generated by Django 4.2.5 on 2023-11-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0020_profile_saved_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="post_approval_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
