# Generated by Django 4.2.5 on 2023-11-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0022_notificationlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationLike",
        ),
    ]
