# Generated by Django 4.2.5 on 2023-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0024_likenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="likenotification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
