# Generated by Django 4.2.5 on 2023-11-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_profile", "0001_initial"),
        ("social_network", "0025_likenotification_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_posts_user",
            field=models.ManyToManyField(
                related_name="saved_by_profiles_user", to="social_profile.postuser"
            ),
        ),
    ]
