# Generated by Django 4.2.5 on 2023-11-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0026_profile_saved_posts_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="interested",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
