# Generated by Django 4.2.5 on 2023-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_network",
            "0027_profile_address_profile_interested_profile_language_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="marital",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("dating", "Dating"),
                    ("married", "Married"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
