# Generated by Django 4.2.5 on 2023-11-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0028_profile_marital"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="background_pics"),
        ),
    ]
