from django.urls import path,re_path
from . import views
app_name ="social_profile"
urlpatterns = [
    path("", views.profile_user, name="profile"),
    path("post_user", views.post_user, name="post_user"),
    path("add_comment_user/<int:post_id>/", views.add_comment_user, name="add_comment_user"),
    path("like_comment_user/<int:comment_id>/", views.like_comment_user, name='like_comment_user'),
    path("like_post/", views.like_post_user, name="like_post"),
    path("add_reply_user/<int:comment_id>/", views.add_reply_user, name="add_reply_user"),
    path("like_reply_user/<int:reply_id>/", views.like_reply_user, name="like_reply_user"),
    path('edit_comment_user/<int:comment_id>/', views.edit_comment_user, name='edit_comment_user'),
    path('delete_comment_user/<int:comment_id>/', views.delete_comment_user, name='delete_comment_user'),
    path('delete_reply_user/<int:reply_id>/', views.delete_reply_user, name='delete_reply_user'),
    path('edit_reply_user/<int:reply_id>/', views.edit_reply_user, name='edit_reply_user'),
    path('save_post_user/<int:post_id>/', views.save_post_user, name='save_post_user'),
    path('unsave_post_user/<int:post_id>/', views.unsave_post_user, name='unsave_post_user'),
    path('edit-post_user/<int:post_id>/', views.edit_post_user, name='edit_post_user'),
    path('delete-image/<int:image_id>/', views.delete_image, name='delete_image'),
    path('delete-video/<int:video_id>/', views.delete_video, name='delete_video'),
    path('hide_post_user/<int:post_id>/', views.hide_post_user, name='hide_post_user'),
    path('delete-post_user/<int:post_id>/', views.delete_post_user, name='delete_post_user'),
    path('close_comment_user/<int:post_id>/', views.close_comment_user, name='close_comment_user'),
    path('open_comment_user/<int:post_id>/', views.open_comment_user, name='open_comment_user'),
    path('detail_image_post/<int:image_id>/', views.detail_image_post, name='detail_image_post'),
    path('detail_image_profile/<int:user_id>/<int:image_id>/', views.detail_image_profile, name='detail_image_profile'),
    path('detail_image_comment/<int:image_id>/', views.detail_image_comment, name='detail_image_comment'),
    path('remove_image_from_album/<int:album_id>/<int:image_id>/', views.delete_image_from_album, name='remove_image_from_album'),
    path('post/<int:post_image_id>/', views.post_detail_user, name='post_detail_user'),
    path('edit-profile-user/<int:user_id>/', views.edit_profile_user, name='edit_profile_user'),
    path('change-password/', views.change_password, name='change_password'),
    path('add_work_user/', views.add_work_user, name='add_work_user'),
    path('add_education_user/', views.add_education_user, name='add_education_user'),
    path('edit_work_user/<int:pk>/', views.edit_work_user, name='edit_work_user'),
    path('edit_education_user/<int:pk>/', views.edit_education_user, name='edit_education_user'),
    path('delete_work_user/<int:pk>/', views.delete_work_user, name='delete_work_user'),
    path('delete_education_user/<int:pk>/', views.delete_education_user, name='delete_education_user'),
    path('add_places_user/', views.add_places_user, name='add_places_user'),
    path('edit_places_user/<int:pk>/', views.edit_places_user, name='edit_places_user'),
    path('delete_places_user/<int:pk>/', views.delete_places_user, name='delete_places_user'),
    path('send_friend_request/<int:pk>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:pk>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:pk>/', views.reject_friend_request, name='reject_friend_request'),
    path('block_user/<int:pk>/', views.block_user, name='block_user'),
    path('unblock_user/<int:pk>/', views.unblock_user, name='unblock_user'),
    path('unfriend_user/<int:pk>/', views.unfriend_user, name='unfriend_user'),
    path('follow_user/<int:pk>/', views.follow_user, name='follow_user'),
    path('unfollow_user/<int:pk>/', views.unfollow_user, name='unfollow_user'),
    path('friend_request_list/', views.friend_request_list, name='friend_request_list'),
    path('change_background_avatar/', views.change_background_avatar, name='change_background_avatar'),
    path('profile/<int:pk>/', views.view_profile_user, name='view_profile_user'),
    path("newsfeed", views.newsfeed, name="newsfeed"),



]   