# Generated by Django 4.2.5 on 2023-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_profile", "0002_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="images",
            field=models.ManyToManyField(
                related_name="albums", to="social_profile.postimageuser"
            ),
        ),
    ]
