# Generated by Django 4.2.5 on 2023-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_profile", "0008_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="postuser",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friend", "Friend"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
