# Generated by Django 4.2.5 on 2023-11-29 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("social_profile", "0010_friendpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
